"use client";

import Link from 'next-intl/link';
import React, { useEffect, useRef, useState } from "react";
import { useTranslations } from 'next-intl';

import "@/public/tailadmin/css/satoshi.css";
import "@/public/tailadmin/css/style.css";

export const metadata = {
    title: 'KDPLAYBACK | DASHBOARD',
    description: 'KDPLAYBACK',
    keywords: 'subcribe youtube ranking, hololive, vtuber, pewdiepie, nextjs',
    viewport: 'width=device-width',
    openGraph: {
        title: 'Twitter',
        description: 'Generated by create next app Twitter',
    }
}

export default function SwitcherOne() {

    const [enabled, setEnabled] = useState(false);

    return (
        <div>
            <label
                htmlFor="toggle1"
                className="flex cursor-pointer select-none items-center"
            >
                <div className="relative">
                    <input
                        type="checkbox"
                        id="toggle1"
                        className="sr-only"
                        onChange={() => {
                            setEnabled(!enabled);
                        }}
                    />
                    <div className="block h-8 w-14 rounded-full bg-meta-9 dark:bg-[#5A616B]"></div>
                    <div className={`absolute left-1 top-1 h-6 w-6 rounded-full bg-white transition ${enabled && "!right-1 !translate-x-full !bg-primary dark:!bg-white"
                            }`}
                    ></div>
                </div>
            </label>
        </div>
    )
}
