import Image from "next/image";
import { useTranslations } from 'next-intl';

// import "jsvectormap/dist/css/jsvectormap.css";
// import "flatpickr/dist/flatpickr.min.css";
import "@/public/tailadmin/css/satoshi.css";
import "@/public/tailadmin/css/style.css";

import Sidebar from '../components/admin/Sidebar';
import Header from '../components/admin/Header';
import Breadcrumb from '../components/admin/Breadcrumb';

import { FaRegTrashAlt } from "react-icons/fa";
import { MdOutlineFileDownload } from "react-icons/md";
import { PiEyeLight } from "react-icons/pi";

export const metadata = {
    title: 'KDPLAYBACK | ABOUT US',
    description: 'KDPLAYBACK',
    keywords: 'subcribe youtube ranking, hololive, vtuber, pewdiepie, nextjs',
    viewport: 'width=device-width',
    openGraph: {
        title: 'Twitter',
        description: 'Generated by create next app Twitter',
    }
}

export default function Table() {

    // const tAbout = useTranslations('about');

    return (
        <div className="dark:bg-boxdark-2 dark:text-bodydark">
            <div className="flex h-screen overflow-hidden">
                <Sidebar />

                <div className="relative flex flex-1 flex-col overflow-y-auto overflow-x-hidden">
                    <Header />

                    <main>
                        <div className="mx-auto max-w-screen-2xl p-4 md:p-6 2xl:p-10">
                            <Breadcrumb
                                pageParent="Dashboard"
                                pageName="Table"
                            />

                            <div className="rounded-sm border border-stroke bg-white px-5 pb-2.5 pt-6 shadow-default dark:border-strokedark dark:bg-boxdark sm:px-7.5 xl:pb-1">
                                <h4 className="mb-6 text-xl font-semibold text-black dark:text-white">
                                    Top Channels
                                </h4>

                                <div className="flex flex-col">
                                    <div className="grid grid-cols-3 rounded-sm bg-gray-2 dark:bg-meta-4 sm:grid-cols-5">
                                        <div className="p-2.5 xl:p-5">
                                            <h5 className="text-sm font-medium uppercase xsm:text-base">
                                                Source
                                            </h5>
                                        </div>
                                        <div className="p-2.5 text-center xl:p-5">
                                            <h5 className="text-sm font-medium uppercase xsm:text-base">
                                                Visitors
                                            </h5>
                                        </div>
                                        <div className="p-2.5 text-center xl:p-5">
                                            <h5 className="text-sm font-medium uppercase xsm:text-base">
                                                Revenues
                                            </h5>
                                        </div>
                                        <div className="hidden p-2.5 text-center sm:block xl:p-5">
                                            <h5 className="text-sm font-medium uppercase xsm:text-base">
                                                Sales
                                            </h5>
                                        </div>
                                        <div className="hidden p-2.5 text-center sm:block xl:p-5">
                                            <h5 className="text-sm font-medium uppercase xsm:text-base">
                                                Conversion
                                            </h5>
                                        </div>
                                    </div>

                                    <div class="grid grid-cols-3 sm:grid-cols-5 border-b border-stroke dark:border-strokedark">
                                        <div className="flex items-center gap-3 p-2.5 xl:p-5">
                                            <div className="flex-shrink-0">
                                                <Image src="/images/brand/brand-01.svg" alt="Brand" width={48} height={48} />
                                            </div>
                                            <p className="hidden text-black dark:text-white sm:block">
                                                Google
                                            </p>
                                        </div>

                                        <div className="flex items-center justify-center p-2.5 xl:p-5">
                                            <p className="text-black dark:text-white">3.5K</p>
                                        </div>

                                        <div className="flex items-center justify-center p-2.5 xl:p-5">
                                            <p className="text-meta-3">$5,768</p>
                                        </div>

                                        <div className="hidden items-center justify-center p-2.5 sm:flex xl:p-5">
                                            <p className="text-black dark:text-white">590</p>
                                        </div>

                                        <div className="hidden items-center justify-center p-2.5 sm:flex xl:p-5">
                                            <p className="text-meta-5">4.8%</p>
                                        </div>
                                    </div>

                                    <div class="grid grid-cols-3 sm:grid-cols-5 border-b border-stroke dark:border-strokedark">
                                        <div class="flex items-center gap-3 p-2.5 xl:p-5">
                                            <div class="flex-shrink-0">
                                                <Image src="/images/brand/brand-02.svg" alt="Brand" width={48} height={48} />
                                            </div>
                                            <p class="hidden text-black dark:text-white sm:block">Twitter</p>
                                        </div>
                                        <div class="flex items-center justify-center p-2.5 xl:p-5">
                                            <p class="text-black dark:text-white">2.2K</p>
                                        </div>
                                        <div class="flex items-center justify-center p-2.5 xl:p-5">
                                            <p class="text-meta-3">$4,635</p>
                                        </div>
                                        <div class="hidden items-center justify-center p-2.5 sm:flex xl:p-5">
                                            <p class="text-black dark:text-white">467</p>
                                        </div>
                                        <div class="hidden items-center justify-center p-2.5 sm:flex xl:p-5">
                                            <p class="text-meta-5">4.3%</p>
                                        </div>
                                    </div>

                                    <div class="grid grid-cols-3 sm:grid-cols-5 ">
                                        <div class="flex items-center gap-3 p-2.5 xl:p-5">
                                            <div class="flex-shrink-0">
                                                <Image src="/images/brand/brand-02.svg" alt="Brand" width={48} height={48} />
                                            </div>
                                            <p class="hidden text-black dark:text-white sm:block">Last no border</p>
                                        </div>
                                        <div class="flex items-center justify-center p-2.5 xl:p-5">
                                            <p class="text-black dark:text-white">2.2K</p>
                                        </div>
                                        <div class="flex items-center justify-center p-2.5 xl:p-5">
                                            <p class="text-meta-3">$4,635</p>
                                        </div>
                                        <div class="hidden items-center justify-center p-2.5 sm:flex xl:p-5">
                                            <p class="text-black dark:text-white">467</p>
                                        </div>
                                        <div class="hidden items-center justify-center p-2.5 sm:flex xl:p-5">
                                            <p class="text-meta-5">4.3%</p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div className="rounded-sm border border-stroke bg-white shadow-default dark:border-strokedark dark:bg-boxdark mt-5">
                                <div className="px-4 py-6 md:px-6 xl:px-7.5">
                                    <h4 className="text-xl font-semibold text-black dark:text-white">
                                        Top Products
                                    </h4>
                                </div>

                                <div className="grid grid-cols-6 border-t border-stroke px-4 py-4.5 dark:border-strokedark sm:grid-cols-8 md:px-6 2xl:px-7.5">
                                    <div className="col-span-3 flex items-center">
                                        <p className="font-medium">Product Name</p>
                                    </div>
                                    <div className="col-span-2 hidden items-center sm:flex">
                                        <p className="font-medium">Category</p>
                                    </div>
                                    <div className="col-span-1 flex items-center">
                                        <p className="font-medium">Price</p>
                                    </div>
                                    <div className="col-span-1 flex items-center">
                                        <p className="font-medium">Sold</p>
                                    </div>
                                    <div className="col-span-1 flex items-center">
                                        <p className="font-medium">Profit</p>
                                    </div>
                                </div>

                                <div className="grid grid-cols-6 border-t border-stroke px-4 py-4.5 dark:border-strokedark sm:grid-cols-8 md:px-6 2xl:px-7.5">
                                    <div className="col-span-3 flex items-center">
                                        <div className="flex flex-col gap-4 sm:flex-row sm:items-center">
                                            <div className="h-12.5 w-15 rounded-md">
                                                <Image
                                                    src="/abc.jpg"
                                                    width={60}
                                                    height={50}
                                                    alt="Product"
                                                />
                                            </div>
                                            <p className="text-sm text-black dark:text-white">
                                                Product Name
                                            </p>
                                        </div>
                                    </div>
                                    <div className="col-span-2 hidden items-center sm:flex">
                                        <p className="text-sm text-black dark:text-white">
                                            product.category
                                        </p>
                                    </div>
                                    <div className="col-span-1 flex items-center">
                                        <p className="text-sm text-black dark:text-white">
                                            $product.price
                                        </p>
                                    </div>
                                    <div className="col-span-1 flex items-center">
                                        <p className="text-sm text-black dark:text-white">product.sold</p>
                                    </div>
                                    <div className="col-span-1 flex items-center">
                                        <p className="text-sm text-meta-3">$product.profit</p>
                                    </div>
                                </div>
                            </div>


                            <div className="rounded-sm border border-stroke bg-white px-5 pb-2.5 pt-6 shadow-default dark:border-strokedark dark:bg-boxdark sm:px-7.5 xl:pb-1 mt-5">
                                <div className="max-w-full overflow-x-auto">
                                    <table className="w-full table-auto">
                                        <thead>
                                            <tr className="bg-gray-2 text-left dark:bg-meta-4">
                                                <th className="min-w-[220px] px-4 py-4 font-medium text-black dark:text-white xl:pl-11">
                                                    Package
                                                </th>
                                                <th className="min-w-[150px] px-4 py-4 font-medium text-black dark:text-white">
                                                    Invoice date
                                                </th>
                                                <th className="min-w-[120px] px-4 py-4 font-medium text-black dark:text-white">
                                                    Status
                                                </th>
                                                <th className="px-4 py-4 font-medium text-black dark:text-white">
                                                    Actions
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td class="border-b border-[#eee] px-4 py-5 pl-9 dark:border-strokedark xl:pl-11">
                                                    <h5 class="font-medium text-black dark:text-white">Free package</h5>
                                                    <p class="text-sm">$0</p>
                                                </td>
                                                <td class="border-b border-[#eee] px-4 py-5 dark:border-strokedark">
                                                    <p class="text-black dark:text-white">Jan 13,2023</p>
                                                </td>
                                                <td class="border-b border-[#eee] px-4 py-5 dark:border-strokedark">
                                                    <p class="inline-flex rounded-full bg-opacity-10 px-3 py-1 text-sm font-medium bg-success text-success">Paid</p>
                                                </td>
                                                <td class="border-b border-[#eee] px-4 py-5 dark:border-strokedark">
                                                    <div class="flex items-center space-x-3.5">
                                                        <button class="hover:text-primary">
                                                            <PiEyeLight />
                                                        </button>
                                                        <button class="hover:text-primary">
                                                            <MdOutlineFileDownload />
                                                        </button>
                                                        <button class="hover:text-primary">
                                                            <FaRegTrashAlt />
                                                        </button>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="border-b border-[#eee] px-4 py-5 pl-9 dark:border-strokedark xl:pl-11">
                                                    <h5 class="font-medium text-black dark:text-white">Free package</h5>
                                                    <p class="text-sm">$0</p>
                                                </td>
                                                <td class="border-b border-[#eee] px-4 py-5 dark:border-strokedark">
                                                    <p class="text-black dark:text-white">Jan 13,2023</p>
                                                </td>
                                                <td class="border-b border-[#eee] px-4 py-5 dark:border-strokedark">
                                                    <p class="inline-flex rounded-full bg-opacity-10 px-3 py-1 text-sm font-medium bg-danger text-danger">Unpaid</p>
                                                </td>
                                                <td class="border-b border-[#eee] px-4 py-5 dark:border-strokedark">
                                                    <div class="flex items-center space-x-3.5">
                                                        <button class="hover:text-primary">
                                                            <PiEyeLight />
                                                        </button>
                                                        <button class="hover:text-primary">
                                                            <MdOutlineFileDownload />
                                                        </button>
                                                        <button class="hover:text-primary">
                                                            <FaRegTrashAlt />
                                                        </button>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="border-b border-[#eee] px-4 py-5 pl-9 dark:border-strokedark xl:pl-11">
                                                    <h5 class="font-medium text-black dark:text-white">Free package</h5>
                                                    <p class="text-sm">$0</p>
                                                </td>
                                                <td class="border-b border-[#eee] px-4 py-5 dark:border-strokedark">
                                                    <p class="text-black dark:text-white">Jan 13,2023</p>
                                                </td>
                                                <td class="border-b border-[#eee] px-4 py-5 dark:border-strokedark">
                                                    <p class="inline-flex rounded-full bg-opacity-10 px-3 py-1 text-sm font-medium bg-warning text-warning">Pending</p>
                                                </td>
                                                <td class="border-b border-[#eee] px-4 py-5 dark:border-strokedark">
                                                    <div class="flex items-center space-x-3.5">
                                                        <button class="hover:text-primary">
                                                            <PiEyeLight />
                                                        </button>
                                                        <button class="hover:text-primary">
                                                            <MdOutlineFileDownload />
                                                        </button>
                                                        <button class="hover:text-primary">
                                                            <FaRegTrashAlt />
                                                        </button>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </main>
                </div>
            </div>
        </div >
    );
}
