import { useTranslations } from 'next-intl';
import { FaTwitter } from "react-icons/fa";

// import "@/public/asset/youtube-ranking/css/style.css";
// import "@/public/asset/youtube-ranking/css/bootstrap.min.css";

import Navbar from '../components/frontend/Navbar';

export const metadata = {
    title: 'KDPLAYBACK | ABOUT US',
    description: 'KDPLAYBACK',
    keywords: 'subcribe youtube ranking, hololive, vtuber, pewdiepie, nextjs',
    viewport: 'width=device-width',
    openGraph: {
        title: 'Twitter',
        description: 'Generated by create next app Twitter',
    }
}

export default function About() {

    const tAbout = useTranslations('about');

    return (
        <div>
            <Navbar />
            <h3 className='mt-10 text-center'>{tAbout('title')}</h3>
            <div className="container">
                <div className="main-body">
                    <div className="row">
                        <div className="col-lg-8">
                            <div className="card">
                                <div className="card-body">
                                    <div className="row mb-3 px-3">
                                        {tAbout('description')}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="col-lg-4">
                            <div className="card mb-10">
                                <div className="card-body">
                                    <ul className="list-group list-group-flush">
                                        <li className="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                            <h6 className="mb-0">Website</h6>
                                            <span className="text-secondary">https://bootdey.com</span>
                                        </li>
                                        <li className="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                            <h6 className="mb-0">YouTube</h6>
                                            <a href="https://www.youtube.com/@KINGDOMNVHAI" target="_blank" className="text-secondary text-deco-none">
                                                KINGDOM NVHAI
                                            </a>
                                        </li>
                                        <li className="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                            <h6 className="mb-0">Twitter</h6>
                                            <a href="https://twitter.com/KNvhai" target="_blank" className="text-secondary text-deco-none">
                                                @KNvhai
                                            </a>
                                        </li>
                                        <li className="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                            <h6 className="mb-0">Facebook</h6>
                                            <a href="https://www.facebook.com/kingdomnvhai.info/" target="_blank" className="text-secondary text-deco-none">
                                                KINGDOM NVHAI
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}
