import { useTranslations } from 'next-intl';

// import "jsvectormap/dist/css/jsvectormap.css";
// import "flatpickr/dist/flatpickr.min.css";
import "@/public/tailadmin/css/satoshi.css";
import "@/public/tailadmin/css/style.css";

import Sidebar from '../components/admin/Sidebar';
import Header from '../components/admin/Header';
import Breadcrumb from '../components/admin/Breadcrumb';
import CheckboxOne from '../components/admin/CheckboxOne';
import SelectGroupTwo from '../components/admin/SelectGroupTwo';
import SwitcherOne from './view/SwitcherOne';

export const metadata = {
    title: 'KDPLAYBACK | FORM ELEMENTS',
    description: 'KDPLAYBACK',
    keywords: 'subcribe youtube ranking, hololive, vtuber, pewdiepie, nextjs',
    viewport: 'width=device-width',
    openGraph: {
        title: 'Twitter',
        description: 'Generated by create next app Twitter',
    }
}

export default function FormElements() {

    const tDashboard = useTranslations('dashboard');

    return (
        <div className="dark:bg-boxdark-2 dark:text-bodydark">
            <div className="flex h-screen overflow-hidden">
                <Sidebar />

                <div className="relative flex flex-1 flex-col overflow-y-auto overflow-x-hidden">
                    <Header />

                    <main>
                        <div className="mx-auto max-w-screen-2xl p-4 md:p-6 2xl:p-10">
                            <Breadcrumb
                                pageParent="Dashboard"
                                pageName="FormElements"
                            />

                            <div class="grid grid-cols-1 gap-9 sm:grid-cols-2">
                                <div class="flex flex-col gap-9">
                                    <div class="rounded-sm border border-stroke bg-white shadow-default dark:border-strokedark dark:bg-boxdark">
                                        <div class="border-b border-stroke px-6.5 py-4 dark:border-strokedark">
                                            <h3 class="font-medium text-black dark:text-white">Input Fields</h3>
                                        </div>
                                        <div className="flex flex-col gap-5.5 p-6.5">
                                            <div>
                                                <label className="mb-3 block text-sm font-medium text-black dark:text-white">
                                                    Default Input
                                                </label>
                                                <input
                                                    type="text"
                                                    placeholder="Default Input"
                                                    className="w-full rounded-lg border-[1.5px] border-stroke bg-transparent px-5 py-3 text-black outline-none transition focus:border-primary active:border-primary disabled:cursor-default disabled:bg-whiter dark:border-form-strokedark dark:bg-form-input dark:text-white dark:focus:border-primary"
                                                />
                                            </div>

                                            <div>
                                                <label className="mb-3 block text-sm font-medium text-black dark:text-white">
                                                    Active Input
                                                </label>
                                                <input
                                                    type="text"
                                                    placeholder="Active Input"
                                                    className="w-full rounded-lg border-[1.5px] border-primary bg-transparent px-5 py-3 text-black outline-none transition focus:border-primary active:border-primary disabled:cursor-default disabled:bg-whiter dark:bg-form-input dark:text-white"
                                                />
                                            </div>

                                            <div>
                                                <label className="mb-3 block text-sm font-medium text-black dark:text-white">
                                                    Disabled label
                                                </label>
                                                <input
                                                    type="text"
                                                    placeholder="Disabled label"
                                                    disabled
                                                    className="w-full rounded-lg border-[1.5px] border-stroke bg-transparent px-5 py-3 text-black outline-none transition focus:border-primary active:border-primary disabled:cursor-default disabled:bg-whiter dark:border-form-strokedark dark:bg-form-input dark:text-white dark:focus:border-primary dark:disabled:bg-black"
                                                />
                                            </div>
                                        </div>
                                    </div>

                                    {/* <!-- Toggle switch input --> */}
                                    <div className="rounded-sm border border-stroke bg-white shadow-default dark:border-strokedark dark:bg-boxdark">
                                        <div className="border-b border-stroke px-6.5 py-4 dark:border-strokedark">
                                            <h3 className="font-medium text-black dark:text-white">
                                                Toggle switch input
                                            </h3>
                                        </div>
                                        <div className="flex flex-col gap-5.5 p-6.5">
                                            <SwitcherOne />

                                        </div>
                                    </div>

                                    {/* <!-- Time and date --> */}
                                    <div className="rounded-sm border border-stroke bg-white shadow-default dark:border-strokedark dark:bg-boxdark">
                                        <div className="border-b border-stroke px-6.5 py-4 dark:border-strokedark">
                                            <h3 className="font-medium text-black dark:text-white">
                                                Time and date
                                            </h3>
                                        </div>
                                        <div className="flex flex-col gap-5.5 p-6.5">
                                        </div>
                                    </div>

                                    {/* <!-- File upload --> */}
                                    <div className="rounded-sm border border-stroke bg-white shadow-default dark:border-strokedark dark:bg-boxdark">
                                        <div className="border-b border-stroke px-6.5 py-4 dark:border-strokedark">
                                            <h3 className="font-medium text-black dark:text-white">
                                                File upload
                                            </h3>
                                        </div>
                                        <div className="flex flex-col gap-5.5 p-6.5">
                                            <div>
                                                <label className="mb-3 block text-sm font-medium text-black dark:text-white">
                                                    Attach file
                                                </label>
                                                <input
                                                    type="file"
                                                    className="w-full cursor-pointer rounded-lg border-[1.5px] border-stroke bg-transparent outline-none transition file:mr-5 file:border-collapse file:cursor-pointer file:border-0 file:border-r file:border-solid file:border-stroke file:bg-whiter file:px-5 file:py-3 file:hover:bg-primary file:hover:bg-opacity-10 focus:border-primary active:border-primary disabled:cursor-default disabled:bg-whiter dark:border-form-strokedark dark:bg-form-input dark:file:border-form-strokedark dark:file:bg-white/30 dark:file:text-white dark:focus:border-primary"
                                                />
                                            </div>

                                            <div>
                                                <label className="mb-3 block text-sm font-medium text-black dark:text-white">
                                                    Attach file
                                                </label>
                                                <input
                                                    type="file"
                                                    className="w-full rounded-md border border-stroke p-3 outline-none transition file:mr-4 file:rounded file:border-[0.5px] file:border-stroke file:bg-[#EEEEEE] file:px-2.5 file:py-1 file:text-sm focus:border-primary file:focus:border-primary active:border-primary disabled:cursor-default disabled:bg-whiter dark:border-form-strokedark dark:bg-form-input dark:file:border-strokedark dark:file:bg-white/30 dark:file:text-white"
                                                />
                                            </div>
                                        </div>
                                    </div>

                                    <div class="rounded-sm border border-stroke bg-white shadow-default dark:border-strokedark dark:bg-boxdark">
                                        <div class="border-b border-stroke px-6.5 py-4 dark:border-strokedark">
                                            <h3 class="font-medium text-black dark:text-white">File Drop Zone</h3>
                                        </div>
                                        <div class="p-6.5">
                                            <form class="dropzone rounded-md !border-dashed !border-bodydark1 bg-gray hover:!border-primary dark:!border-strokedark dark:bg-graydark dark:hover:!border-primary dz-clickable" id="demo-upload" action="/upload">
                                                <div class="dz-message">
                                                    <div class="mb-2.5 flex justify-center">
                                                        <div class="flex h-15 w-15 items-center justify-center rounded-full bg-white text-black shadow-10 dark:bg-black dark:text-white">
                                                            <svg class="fill-current" width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                                <g clip-path="url(#clip0_1867_11682)">
                                                                    <path d="M18.75 13.75C18.375 13.75 18.0313 14.0625 18.0313 14.4687V17.25C18.0313 17.5312 17.8125 17.75 17.5312 17.75H2.46875C2.1875 17.75 1.96875 17.5312 1.96875 17.25V14.4687C1.96875 14.0625 1.625 13.75 1.25 13.75C0.875 13.75 0.53125 14.0625 0.53125 14.4687V17.25C0.53125 18.3125 1.375 19.1562 2.4375 19.1562H17.5312C18.5938 19.1562 19.4375 18.3125 19.4375 17.25V14.4687C19.4688 14.0625 19.125 13.75 18.75 13.75Z" fill=""></path>
                                                                    <path d="M5.96875 6.46875L9.3125 3.21875V14.0313C9.3125 14.4063 9.625 14.75 10.0312 14.75C10.4062 14.75 10.75 14.4375 10.75 14.0313V3.21875L14.0937 6.46875C14.2187 6.59375 14.4062 6.65625 14.5938 6.65625C14.7812 6.65625 14.9688 6.59375 15.0938 6.4375C15.375 6.15625 15.3438 5.71875 15.0938 5.4375L10.5 1.0625C10.2187 0.8125 9.78125 0.8125 9.53125 1.0625L4.96875 5.46875C4.6875 5.75 4.6875 6.1875 4.96875 6.46875C5.25 6.71875 5.6875 6.75 5.96875 6.46875Z" fill=""></path>
                                                                </g>
                                                                <defs>
                                                                    <clipPath id="clip0_1867_11682">
                                                                        <rect width="20" height="20" fill="white"></rect>
                                                                    </clipPath>
                                                                </defs>
                                                            </svg>
                                                        </div>
                                                    </div>
                                                    <span class="font-medium text-black dark:text-white">Drop files here to upload</span>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>

                                <div class="flex flex-col gap-3">
                                    <div className="rounded-sm border border-stroke bg-white shadow-default dark:border-strokedark dark:bg-boxdark">
                                        <div className="border-b border-stroke px-6.5 py-4 dark:border-strokedark">
                                            <h3 className="font-medium text-black dark:text-white">
                                                Textarea Fields
                                            </h3>
                                        </div>
                                        <div className="flex flex-col gap-5.5 p-6.5">
                                            <div>
                                                <label className="mb-3 block text-sm font-medium text-black dark:text-white">
                                                    Default textarea
                                                </label>
                                                <textarea
                                                    rows={6}
                                                    placeholder="Default textarea"
                                                    className="w-full rounded-lg border-[1.5px] border-stroke bg-transparent px-5 py-3 text-black outline-none transition focus:border-primary active:border-primary disabled:cursor-default disabled:bg-whiter dark:border-form-strokedark dark:bg-form-input dark:text-white dark:focus:border-primary"
                                                ></textarea>
                                            </div>

                                            <div>
                                                <label className="mb-3 block text-sm font-medium text-black dark:text-white">
                                                    Active textarea
                                                </label>
                                                <textarea
                                                    rows={6}
                                                    placeholder="Active textarea"
                                                    className="w-full rounded-lg border-[1.5px] border-primary bg-transparent px-5 py-3 text-black outline-none transition focus:border-primary active:border-primary disabled:cursor-default disabled:bg-whiter dark:bg-form-input dark:text-white"
                                                ></textarea>
                                            </div>

                                            <div>
                                                <label className="mb-3 block text-sm font-medium text-black dark:text-white">
                                                    Disabled textarea
                                                </label>
                                                <textarea
                                                    rows={6}
                                                    disabled
                                                    placeholder="Disabled textarea"
                                                    className="w-full rounded-lg border-[1.5px] border-stroke bg-transparent px-5 py-3 text-black outline-none transition focus:border-primary active:border-primary disabled:cursor-default disabled:bg-whiter dark:border-form-strokedark dark:bg-form-input dark:text-white dark:focus:border-primary dark:disabled:bg-black"
                                                ></textarea>
                                            </div>
                                        </div>
                                    </div>

                                    <div className="rounded-sm border border-stroke bg-white shadow-default dark:border-strokedark dark:bg-boxdark">
                                        <div className="border-b border-stroke px-6.5 py-4 dark:border-strokedark">
                                            <h3 className="font-medium text-black dark:text-white">
                                                Checkbox and radio
                                            </h3>
                                        </div>
                                        <div className="flex flex-col gap-5.5 p-6.5">
                                            <CheckboxOne />
                                        </div>
                                    </div>

                                    <div className="rounded-sm border border-stroke bg-white shadow-default dark:border-strokedark dark:bg-boxdark">
                                        <div className="border-b border-stroke px-6.5 py-4 dark:border-strokedark">
                                            <h3 className="font-medium text-black dark:text-white">
                                                Select input
                                            </h3>
                                        </div>
                                        <div className="flex flex-col gap-5.5 p-6.5">
                                            <SelectGroupTwo />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </main>
                </div>
            </div>
        </div>
    )
}
