import { useTranslations } from 'next-intl';
import Image from 'next/image';

// import "jsvectormap/dist/css/jsvectormap.css";
// import "flatpickr/dist/flatpickr.min.css";
import "@/public/tailadmin/css/satoshi.css";
import "@/public/tailadmin/css/style.css";

import Sidebar from '../components/admin/Sidebar';
import Header from '../components/admin/Header';
import Breadcrumb from '../components/admin/Breadcrumb';

export const metadata = {
    title: 'KDPLAYBACK | DASHBOARD',
    description: 'KDPLAYBACK',
    keywords: 'subcribe youtube ranking, hololive, vtuber, pewdiepie, nextjs',
    viewport: 'width=device-width',
    openGraph: {
        title: 'Twitter',
        description: 'Generated by create next app Twitter',
    }
}

export default function Invoice() {

    // const tDashboard = useTranslations('dashboard');

    return (
        <div className="dark:bg-boxdark-2 dark:text-bodydark">
            <div className="flex h-screen overflow-hidden">
                <Sidebar />

                <div className="relative flex flex-1 flex-col overflow-y-auto overflow-x-hidden">
                    <Header />

                    <main>
                        <div className="mx-auto max-w-screen-2xl p-4 md:p-6 2xl:p-10">
                            <Breadcrumb
                                pageParent="Dashboard"
                                pageName="Invoice"
                            />

                            <div class="flex flex-col gap-10">
                                <div class="rounded-sm border border-stroke bg-white shadow-default dark:border-strokedark dark:bg-boxdark">
                                    <div class="border-b border-stroke px-4 py-4 dark:border-strokedark sm:px-6 xl:px-9">
                                        <h3 class="font-medium text-black dark:text-white">Style 1</h3>
                                    </div>

                                    <div class="p-4 sm:p-6 xl:p-9">
                                        <div>
                                            <div class="flex flex-col-reverse gap-5 xl:flex-row xl:justify-between">
                                                <div class="flex flex-col gap-4 sm:flex-row xl:gap-9">
                                                    <div>
                                                        <p class="mb-1.5 font-medium text-black dark:text-white">From</p>
                                                        <h4 class="mb-4 text-title-sm2 font-medium leading-[30px] text-black dark:text-white">Roger Culhane</h4>
                                                        <a class="block" href="#"><span class="font-medium">Email: </span>contact@example.com</a>
                                                        <span class="mt-2 block"><span class="font-medium">Address: </span> 2972 Westheimer Rd. Santa Ana.</span>
                                                    </div>
                                                    <div>
                                                        <p class="mb-1.5 font-medium text-black dark:text-white">To</p>
                                                        <h4 class="mb-4 text-title-sm2 font-medium leading-[30px] text-black dark:text-white">Cristofer Levin</h4>
                                                        <a class="block" href="#"><span class="font-medium">Email: </span>contact@example.com</a>
                                                        <span class="mt-2 block">
                                                            <span class="font-medium">Address: </span> New York, USA 2707 Davis Anenue
                                                        </span>
                                                    </div>
                                                </div>
                                                <h3 class="text-2xl font-medium text-black dark:text-white">Order #15478</h3>
                                            </div>
                                            <div class="my-10 rounded-sm border border-stroke p-5 dark:border-strokedark">
                                                <div class="items-center sm:flex">
                                                    <div class="mb-3 mr-6 h-20 w-20 sm:mb-0">

                                                        <Image
                                                            width={80}
                                                            height={80}
                                                            src={"/public/tailadmin/images/user/user-01.png"}
                                                            className="h-full w-full rounded-sm object-cover object-center"
                                                            style={{
                                                                color: "transparent",
                                                                width: "auto",
                                                                height: "auto",
                                                            }}
                                                            alt="User"
                                                        />
                                                    </div>
                                                    <div class="w-full items-center justify-between md:flex">
                                                        <div class="mb-3 md:mb-0">
                                                            <a class="inline-block font-medium text-black hover:text-primary dark:text-white" href="#">Mist Black Triblend</a>
                                                            <p class="flex text-sm font-medium">
                                                                <span class="mr-5"> Color: White </span>
                                                                <span class="mr-5"> Size: Medium </span>
                                                            </p>
                                                        </div>
                                                        <div class="flex items-center md:justify-end">
                                                            <p class="mr-20 font-medium text-black dark:text-white">Qty: 1</p>
                                                            <p class="mr-5 font-medium text-black dark:text-white">$120</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="-mx-4 flex flex-wrap"><div class="w-full px-4 sm:w-1/2 xl:w-3/12">
                                                <div class="mb-10">
                                                    <h4 class="mb-4 text-title-sm2 font-medium leading-[30px] text-black dark:text-white md:text-2xl">Shipping Method</h4>
                                                    <p class="font-medium">FedEx - Take up to 3 working days.</p>
                                                </div>




                                            </div>
                                                <div class="w-full px-4 sm:w-1/2 xl:w-3/12">
                                                    <div class="mb-10">
                                                        <h4 class="mb-4 text-title-sm2 font-medium leading-[30px] text-black dark:text-white md:text-2xl">Payment Method</h4>
                                                        <p class="font-medium">Apply Pay Mastercard **** **** **** 5874</p>
                                                    </div>
                                                </div>
                                                <div class="w-full px-4 xl:w-6/12">
                                                    <div class="mr-10 text-right md:ml-auto">
                                                        <div class="ml-auto sm:w-1/2">
                                                            <p class="mb-4 flex justify-between font-medium text-black dark:text-white">
                                                                <span> Subtotal </span>
                                                                <span> $120.00 </span>
                                                            </p>
                                                            <p class="mb-4 flex justify-between font-medium text-black dark:text-white">
                                                                <span> Shipping Cost (+) </span>
                                                                <span> $10.00 </span>
                                                            </p>
                                                            <p class="mb-4 mt-2 flex justify-between border-t border-stroke pt-6 font-medium text-black dark:border-strokedark dark:text-white">
                                                                <span> Total Payable </span>
                                                                <span> $130.00 </span>
                                                            </p>
                                                        </div>
                                                        <div class="mt-10 flex flex-col justify-end gap-4 sm:flex-row">
                                                            <button class="flex items-center justify-center rounded border border-primary px-8 py-2.5 text-center font-medium text-primary hover:opacity-90">Download Invoice</button>
                                                            <button class="flex items-center justify-center rounded bg-primary px-8 py-2.5 text-center font-medium text-gray hover:bg-opacity-90">Send Invoice</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </main>
                </div>
            </div>
        </div>
    )
}
