import { useTranslations } from 'next-intl';
import { FaTwitter } from "react-icons/fa";

// import "jsvectormap/dist/css/jsvectormap.css";
// import "flatpickr/dist/flatpickr.min.css";
import "@/public/tailadmin/css/satoshi.css";
import "@/public/tailadmin/css/style.css";

import Navbar from '../components/admin/Sidebar';

export const metadata = {
    title: 'KDPLAYBACK | DASHBOARD',
    description: 'KDPLAYBACK',
    keywords: 'subcribe youtube ranking, hololive, vtuber, pewdiepie, nextjs',
    viewport: 'width=device-width',
    openGraph: {
        title: 'Twitter',
        description: 'Generated by create next app Twitter',
    }
}

export default function Dashboard() {

    const tAbout = useTranslations('dashboard');

    return (
        <div class="dark:bg-boxdark-2 dark:text-bodydark">
            <div class="flex h-screen overflow-hidden">
                <Navbar />

            </div>
        </div>
    )
}
